Objetivo 4 [IV-21-22]
alexespana/BarPower pull request #24
Opened 2021-11-01 18:34 UTC by alexespana

En este Pull Request se ha trabajado en los siguientes contenidos:
* Se ha convertido cada visita en un **objeto valor** (perfeccionando el objetivo 2) trabajando en las tareas #21 , #22 y #23 resolviendo la HU #9 .
* Cambiado el task runner invoke por poethepoet (que funciona bien con poetry) y todo lo relacionado con ello (justificación, comandos, etc).
* Elegido un marco de tests: **pytest**
* Elegida biblioteca de aserciones para tests: **la proporcionada por pytest**
* Testeado el comportamiento de la clase Visits mediante el uso de fixtures.
* Justificación del marco de test elegido y la bilbioteca de aserciones.

2021-11-02 19:06 UTC, alexespana commented
Listo para revisión

2021-11-04 15:12 UTC, alexespana commented on bar_power/Visits.py
> +        self.v_visits.append(bar_power.Visit.Visit(hour, client_type))
Sí, la verdad es que tuve bastantes problemas con los import para que me funcionase. Voy a intentar solucionarlo.

2021-11-04 17:40 UTC, alexespana commented
Listo para revisión.

2021-11-05 08:05 UTC, JJ approved these changes
Vamos a pasarlo, aunque el testeo de la lógica de negocio es bastante mínimo.

2021-11-05 08:05 UTC, JJ commented on bar_power/Visit.py
> +@dataclass(frozen=True)     # Cualquier asignación producirá una excepción
Con que pongas el comentario una vez, ya vale.

2021-11-05 08:05 UTC, JJ commented on bar_power/Visits.py
> +        self.v_visits = []
Si vas a acceder a esto por horas, ¿cómo vas a obtener las que haya en la misma hora?

2021-11-05 08:05 UTC, JJ commented on bar_power/Visits.py
> +            raise AttributeError("El tipo de cliente especificado no es correcto.")
¿Seguro que es AttributeError el más adecuado?

2021-11-05 08:12 UTC, JJ requested changes
Estoy revisando y no puede pasar. Sigues sin hacer cambios refiriéndonte a un issue y a las historias de usuario. El testeo de la lógina de negocio es mínimo. Por favor, sigue las buenas prácticas en el desarrollo de las que hemos hablado tantas veces.

2021-11-05 12:03 UTC, alexespana commented on bar_power/Visits.py
> +            raise AttributeError("El tipo de cliente especificado no es correcto.")
No, mejor TypeError.

2021-11-05 12:03 UTC, alexespana commented on bar_power/Visit.py
> +@dataclass(frozen=True)     # Cualquier asignación producirá una excepción
Perfecto :+1:

2021-11-05 13:00 UTC, alexespana commented
Listo para revisión

2021-11-05 13:00 UTC, JJ requested changes
:+1:

2021-11-05 17:03 UTC, merged