Objetivo 5 [IV-21-22]
alexespana/barpower pull request #31
Opened 2021-11-16 01:01 UTC by alexespana

2021-11-16 23:31 UTC, alexespana commented
Listo para revisión.

2021-11-18 02:34 UTC, alexespana commented
Listo para revisión.

2021-11-18 05:41 UTC, JJ requested changes
Los errores principales son copiar a donde se va a superponer el código; el resto no tienen tanta importancia. Tampoco hay una buena justificación del contenedor base.

2021-11-18 05:41 UTC, JJ commented on .github/workflows/build.yml
> +on:
Esto lo va a actualizar siempre.

2021-11-18 05:41 UTC, JJ commented on .github/workflows/sync.yml
> +    - main
Podías ponerlo que se activara solo cuando se cambia el README.md

2021-11-18 05:41 UTC, JJ commented on Dockerfile
> +RUN chown dockertest:dockertest /app/test
Esto no tiene ningún efecto.

2021-11-18 05:41 UTC, JJ commented on Dockerfile
> +COPY pyproject.toml /app/test/
Tampoco servirá de nada, esto se borra.

2021-11-18 05:41 UTC, JJ commented on Dockerfile
> +RUN /usr/local/bin/python -m pip install --upgrade pip
¿Seguro que esta es la versión del contenedor? ¿No será mejor que uses simplemente python?

2021-11-18 05:41 UTC, JJ commented on README.md
> +base se ha elegido el oficial de python, en la versión 3.8, ya que nuestro código fuente está compilado con dicha versión. Lo primero que necesitamos
Tu código fuente tendrá que compilarse con la versión que sea necesaria. No es una justificación.

2021-11-18 09:04 UTC, alexespana commented on .github/workflows/sync.yml
> +    - main
Es verdad, hecho.

2021-11-18 09:20 UTC, alexespana commented on .github/workflows/build.yml
> +on:
Más bien tendría que actualizarse si cambia el archivo Dockerfile o cambia el archivo pyproject.toml.

2021-11-19 16:01 UTC, alexespana commented on Dockerfile
> +RUN /usr/local/bin/python -m pip install --upgrade pip
Sí:+1:

2021-11-19 16:02 UTC, alexespana commented on Dockerfile
> +COPY pyproject.toml /app/test/
Cierto, no tiene sentido.

2021-11-20 10:59 UTC, alexespana commented on Dockerfile
> +RUN chown dockertest:dockertest /app/test
Simplemente lo puse porque al pasar los tests se producían unos warnings debido a que pytest intentaba escribir cache en la carpeta.

2021-11-20 11:00 UTC, alexespana commented on README.md
> +base se ha elegido el oficial de python, en la versión 3.8, ya que nuestro código fuente está compilado con dicha versión. Lo primero que necesitamos
Arreglado :+1:

2021-11-20 11:00 UTC, alexespana commented
Listo para revisión

2021-11-20 12:59 UTC, JJ commented on Dockerfile
> +RUN chown dockertest:dockertest /app/test
Va a producir los mismos warnings, porque no tienes permiso de escritura en esa carpeta.

2021-11-20 13:02 UTC, JJ requested changes
El error principal es que no se está ejecutando desde donde debe, /app/test porque el workdir no es el correcto. Por lo demás, bastante mejorado.

2021-11-20 13:02 UTC, JJ commented on Dockerfile
> +
El workdir sigue sin ser el correcto. No es el mismo para la instalación que para el test

2021-11-20 13:02 UTC, JJ commented on Dockerfile
> +RUN pip3 install poetry && \
Una vez que instales poetry todas las instalaciones las debes hacer desde él. Si poethepoet es una de las dependencias, mejor que se haga desde ahí (porque tendrá en cuenta poetry.lock y demás)

2021-11-20 15:14 UTC, alexespana commented on Dockerfile
> +
¿Se podrían usar dos instrucciones WORKDIR en el Dockerfile? Así cambio el directorio de trabajo para realizar la instalación.

2021-11-20 15:34 UTC, alexespana commented on Dockerfile
> +RUN chown dockertest:dockertest /app/test
De acuerdo, lo borro entonces

2021-11-20 15:34 UTC, alexespana commented on Dockerfile
> +RUN pip3 install poetry && \
Perfecto, el problema es que poetry crea un entorno e instala ahí las dependencias, entonces para poder lanzar el task runner tendría que hacerse a través del gestor de dependencias (cosa que no creo que tenga mucho sentido).

2021-11-20 15:39 UTC, alexespana commented on Dockerfile
> +RUN pip3 install poetry && \
Bueno, creo que con [esto](https://python-poetry.org/docs/configuration/) podré solucionarlo.

2021-11-21 13:40 UTC, alexespana commented on Dockerfile
> +
Con una me bastaría

2021-11-21 13:45 UTC, alexespana commented on Dockerfile
> +RUN pip3 install poetry && \
> Perfecto, el problema es que poetry crea un entorno e instala ahí las dependencias, entonces para poder lanzar el task runner tendría que hacerse a través del gestor de dependencias (cosa que no creo que tenga mucho sentido).

No me funcionaba bien porque no encuentra poe en el PATH, he estado buscando y mucha gente tenía el mismo problema, finalmente no he podido solucionarlo excepto indicando que no cree el entorno virtual como se indica en el enlace de abajo.

2021-11-21 14:01 UTC, alexespana commented on Dockerfile
> +RUN pip3 install poetry && \
> > Perfecto, el problema es que poetry crea un entorno e instala ahí las dependencias, entonces para poder lanzar el task runner tendría que hacerse a través del gestor de dependencias (cosa que no creo que tenga mucho sentido).
> 
> No me funcionaba bien porque no encuentraba poe en el PATH, he estado buscando y mucha gente tenía el mismo problema, finalmente no he podido solucionarlo sweat excepto indicando que no cree el entorno virtual como se indica en el enlace de arriba.

Sólo pude solucionarlo mediante [esto](https://python-poetry.org/docs/configuration/). Igualmente creo que tiene sentido ya que docker crea un entorno aislado para la ejecución, por lo que tener un virtualenv carece de sentido.

2021-11-21 14:02 UTC, alexespana commented
Listo para revisión.

2021-11-21 18:26 UTC, JJ approved these changes
El obstáculo principal está superado, aunque seguimos sin justificar correctametne las elecciones ténicas mirando las alternativas posibles. Te rogaría que lo corrigieras antes dle siguiente objetivo.

2021-11-21 18:26 UTC, JJ commented on Dockerfile
> +ENV PATH="$PATH:/home/dockertest/.local/bin:${PATH}"
Esto solo va a funcionar durante el build.

2021-11-21 18:26 UTC, JJ commented on Dockerfile
> +FROM python:3.8-slim
Podrías haber cambiado esto, para diferenciarte un poco de... otros.

2021-11-25 18:01 UTC, merged